// apps/server/src/modules/project/core/project.policy.ts
import { ProjectForbiddenError } from './project.errors.js';
import type { ProjectContext, ProjectRole } from './project.types.js';

// ── Capability map — defines what each project role may do ───────────────────

const PROJECT_ROLE_CAPABILITIES: Record<ProjectRole, string[]> = {
  PROJECT_MANAGER: [
    'project:read',
    'project:update',
    'project:lifecycle',
    'project:member:manage',
    'project:settings:update',
    'project:phase:manage',
    'project:cost-code:manage',
    'project:audit:read',
    'project.task.read',
    'project.task.create',
    'project.task.update',
    'project.task.delete',
    'project.calendar.manage',
    'project.dependency.create',
    'project.dependency.delete',
    'project.schedule.recalculate',
    'project.baseline.read',
    'project.baseline.create',
    'project.baseline.activate',
    'project.baseline.delete',
    'project.field-log.read',
    'project.field-log.create',
    'project.field-log.update',
    'project.field-log.submit',
    'project.field-log.lock',
    'project.issue.read',
    'project.issue.create',
    'project.issue.update',
    'project.issue.transition',
    'project.subcontractor.read',
    'project.subcontractor.create',
    'project.subcontractor.update',
    'project.subcontractor.assign',
    'project.material_request.read',
    'project.material_request.create',
    'project.material_request.update',
    'project.material_request.submit',
    'project.material_request.cancel',
    'project.quote.read',
    'project.quote.create',
    'project.quote.update',
    'project.quote.submit',
    'project.quote.accept',
    'project.quote.reject',
    'project.procurement_approval.read',
    'project.procurement_approval.create',
    'project.procurement_approval.approve',
    'project.procurement_approval.reject',
    'project.purchase_order.read',
    'project.purchase_order.create',
    'project.purchase_order.update',
    'project.purchase_order.submit',
    'project.purchase_order.approve',
    'project.purchase_order.send',
    'project.purchase_order.cancel',
    'project.committed_cost.read',
    'project.delivery.read',
    'project.delivery.create',
    'project.delivery.update',
    'project.receipt.read',
    'project.receipt.create',
    'project.receipt.post',
    'project.receipt.void',
    'project.inventory.read',
    'project.inventory.adjust',
    'project.performance.read',
    'project.document.upload',
    'project.document.download',
    'project.document.manage',
    'project.document.version',
    'project.permit.read',
    'project.permit.manage',
    'project.compliance_inspection.read',
    'project.compliance_inspection.manage',
    'project.compliance_record.read',
    'project.compliance_record.manage',
    'project.rfi.read',
    'project.rfi.create',
    'project.rfi.respond',
    'project.rfi.manage',
    'project.submittal.read',
    'project.submittal.create',
    'project.submittal.review',
    'project.submittal.manage',
    'project.quality.read',
    'project.quality.inspect',
    'project.quality.manage_deficiency',
    'project.quality.verify_corrective',
    'project.safety.read',
    'project.safety.report',
    'project.safety.investigate',
    'project.safety.manage',
  ],
  SITE_SUPERVISOR: [
    'project:read',
    'project:update',
    'project:phase:manage',
    'project.task.read',
    'project.task.create',
    'project.task.update',
    'project.calendar.manage',
    'project.dependency.create',
    'project.dependency.delete',
    'project.schedule.recalculate',
    'project.baseline.read',
    'project.baseline.create',
    'project.baseline.activate',
    'project.field-log.read',
    'project.field-log.create',
    'project.field-log.update',
    'project.field-log.submit',
    'project.field-log.lock',
    'project.issue.read',
    'project.issue.create',
    'project.issue.update',
    'project.issue.transition',
    'project.subcontractor.read',
    'project.subcontractor.create',
    'project.subcontractor.update',
    'project.subcontractor.assign',
    'project.material_request.read',
    'project.material_request.create',
    'project.material_request.update',
    'project.material_request.submit',
    'project.material_request.cancel',
    'project.quote.read',
    'project.quote.create',
    'project.quote.update',
    'project.quote.submit',
    'project.quote.accept',
    'project.quote.reject',
    'project.procurement_approval.read',
    'project.purchase_order.read',
    'project.committed_cost.read',
    'project.delivery.read',
    'project.delivery.create',
    'project.delivery.update',
    'project.receipt.read',
    'project.receipt.create',
    'project.receipt.post',
    'project.receipt.void',
    'project.inventory.read',
    'project.inventory.adjust',
    'project.performance.read',
    'project.document.upload',
    'project.document.download',
    'project.document.manage',
    'project.document.version',
    'project.permit.read',
    'project.permit.manage',
    'project.compliance_inspection.read',
    'project.compliance_inspection.manage',
    'project.compliance_record.read',
    'project.compliance_record.manage',
    'project.rfi.read',
    'project.rfi.create',
    'project.rfi.respond',
    'project.rfi.manage',
    'project.submittal.read',
    'project.submittal.create',
    'project.submittal.review',
    'project.submittal.manage',
    'project.quality.read',
    'project.quality.inspect',
    'project.quality.manage_deficiency',
    'project.quality.verify_corrective',
    'project.safety.read',
    'project.safety.report',
    'project.safety.investigate',
    'project.safety.manage',
  ],
  PROJECT_MEMBER: [
    'project:read',
    'project.task.read',
    'project.task.create',
    'project.task.update',
    'project.dependency.create',
    'project.baseline.read',
    'project.field-log.read',
    'project.issue.read',
    'project.issue.create',
    'project.subcontractor.read',
    'project.material_request.read',
    'project.material_request.create',
    'project.material_request.submit',
    'project.quote.read',
    'project.procurement_approval.read',
    'project.purchase_order.read',
    'project.committed_cost.read',
    'project.delivery.read',
    'project.receipt.read',
    'project.inventory.read',
    'project.performance.read',
    'project.document.upload',
    'project.document.download',
    'project.permit.read',
    'project.compliance_inspection.read',
    'project.compliance_record.read',
    'project.rfi.read',
    'project.rfi.create',
    'project.submittal.read',
    'project.submittal.create',
    'project.quality.read',
    'project.safety.read',
    'project.safety.report',
  ],
  FINANCE: ['project:read', 'project:cost-code:manage', 'project.task.read', 'project.baseline.read', 'project.field-log.read', 'project.issue.read', 'project.quote.read', 'project.quote.accept', 'project.quote.reject', 'project.procurement_approval.read', 'project.procurement_approval.create', 'project.procurement_approval.approve', 'project.procurement_approval.reject', 'project.purchase_order.read', 'project.purchase_order.create', 'project.purchase_order.update', 'project.purchase_order.submit', 'project.purchase_order.approve', 'project.purchase_order.send', 'project.purchase_order.cancel', 'project.committed_cost.read', 'project.delivery.read', 'project.receipt.read', 'project.inventory.read', 'project.performance.read', 'project.document.upload', 'project.document.download', 'project.permit.read', 'project.compliance_record.read'],
  PROCUREMENT: ['project:read', 'project.task.read', 'project.baseline.read', 'project.field-log.read', 'project.issue.read', 'project.subcontractor.read', 'project.material_request.read', 'project.material_request.create', 'project.material_request.update', 'project.material_request.submit', 'project.material_request.cancel', 'project.quote.read', 'project.quote.create', 'project.quote.update', 'project.quote.submit', 'project.quote.accept', 'project.quote.reject', 'project.procurement_approval.read', 'project.procurement_approval.create', 'project.purchase_order.read', 'project.purchase_order.create', 'project.purchase_order.update', 'project.purchase_order.submit', 'project.purchase_order.send', 'project.purchase_order.cancel', 'project.committed_cost.read', 'project.delivery.read', 'project.delivery.create', 'project.delivery.update', 'project.receipt.read', 'project.receipt.create', 'project.receipt.post', 'project.receipt.void', 'project.inventory.read', 'project.inventory.adjust', 'project.performance.read', 'project.document.upload', 'project.document.download', 'project.document.version'],
  SUBCONTRACTOR: ['project:read', 'project.task.read', 'project.baseline.read', 'project.field-log.read', 'project.issue.read', 'project.document.download'],
  CLIENT: ['project:read', 'project.task.read', 'project.baseline.read', 'project.field-log.read', 'project.issue.read', 'project.document.download', 'project.rfi.read', 'project.submittal.read'],
};

// ── Org-level permission strings that bypass project membership ───────────────

// An actor with any of these on their orgContext.permissions can act cross-project.
const ORG_LEVEL_AUTHORITY_MAP: Record<string, string[]> = {
  'project:read':              ['project:read:any', 'project:write:any', 'project:admin'],
  'project:update':            ['project:write:any', 'project:admin'],
  'project:lifecycle':         ['project:admin'],
  'project:member:manage':     ['project:admin'],
  'project:settings:update':   ['project:admin'],
  'project:phase:manage':      ['project:write:any', 'project:admin'],
  'project:cost-code:manage':  ['project:write:any', 'project:admin'],
  'project:audit:read':        ['project:read:any', 'project:admin'],
  'project.task.read':         ['project:read:any', 'project:write:any', 'project:admin'],
  'project.task.create':       ['project:write:any', 'project:admin'],
  'project.task.update':       ['project:write:any', 'project:admin'],
  'project.task.delete':       ['project:write:any', 'project:admin'],
  'project.calendar.manage':   ['project:write:any', 'project:admin'],
  'project.dependency.create': ['project:write:any', 'project:admin'],
  'project.dependency.delete': ['project:write:any', 'project:admin'],
  'project.schedule.recalculate': ['project:write:any', 'project:admin'],
  'project.baseline.read':     ['project:read:any', 'project:write:any', 'project:admin'],
  'project.baseline.create':   ['project:write:any', 'project:admin'],
  'project.baseline.activate': ['project:write:any', 'project:admin'],
  'project.baseline.delete':   ['project:write:any', 'project:admin'],
  'project.field-log.read':    ['project:read:any', 'project:write:any', 'project:admin'],
  'project.field-log.create':  ['project:write:any', 'project:admin'],
  'project.field-log.update':  ['project:write:any', 'project:admin'],
  'project.field-log.submit':  ['project:write:any', 'project:admin'],
  'project.field-log.lock':    ['project:write:any', 'project:admin'],
  'project.issue.read':        ['project:read:any', 'project:write:any', 'project:admin'],
  'project.issue.create':      ['project:write:any', 'project:admin'],
  'project.issue.update':      ['project:write:any', 'project:admin'],
  'project.issue.transition':  ['project:write:any', 'project:admin'],
  'project.subcontractor.read':   ['project:read:any', 'project:write:any', 'project:admin'],
  'project.subcontractor.create': ['project:write:any', 'project:admin'],
  'project.subcontractor.update': ['project:write:any', 'project:admin'],
  'project.subcontractor.assign': ['project:write:any', 'project:admin'],
  'project.material_request.read':   ['project:read:any', 'project:write:any', 'project:admin'],
  'project.material_request.create': ['project:write:any', 'project:admin'],
  'project.material_request.update': ['project:write:any', 'project:admin'],
  'project.material_request.submit': ['project:write:any', 'project:admin'],
  'project.material_request.cancel': ['project:write:any', 'project:admin'],
  'project.quote.read':   ['project:read:any', 'project:write:any', 'project:admin'],
  'project.quote.create': ['project:write:any', 'project:admin'],
  'project.quote.update': ['project:write:any', 'project:admin'],
  'project.quote.submit': ['project:write:any', 'project:admin'],
  'project.quote.accept': ['project:write:any', 'project:admin'],
  'project.quote.reject': ['project:write:any', 'project:admin'],
  'project.procurement_approval.read':    ['project:read:any', 'project:write:any', 'project:admin'],
  'project.procurement_approval.create':  ['project:write:any', 'project:admin'],
  'project.procurement_approval.approve': ['project:write:any', 'project:admin'],
  'project.procurement_approval.reject':  ['project:write:any', 'project:admin'],
  'project.purchase_order.read':   ['project:read:any', 'project:write:any', 'project:admin'],
  'project.purchase_order.create': ['project:write:any', 'project:admin'],
  'project.purchase_order.update': ['project:write:any', 'project:admin'],
  'project.purchase_order.submit': ['project:write:any', 'project:admin'],
  'project.purchase_order.approve':['project:write:any', 'project:admin'],
  'project.purchase_order.send':   ['project:write:any', 'project:admin'],
  'project.purchase_order.cancel': ['project:write:any', 'project:admin'],
  'project.committed_cost.read': ['project:read:any', 'project:write:any', 'project:admin'],
  'project.delivery.read':    ['project:read:any', 'project:write:any', 'project:admin'],
  'project.delivery.create':  ['project:write:any', 'project:admin'],
  'project.delivery.update':  ['project:write:any', 'project:admin'],
  'project.receipt.read':     ['project:read:any', 'project:write:any', 'project:admin'],
  'project.receipt.create':   ['project:write:any', 'project:admin'],
  'project.receipt.post':     ['project:write:any', 'project:admin'],
  'project.receipt.void':     ['project:write:any', 'project:admin'],
  'project.inventory.read':   ['project:read:any', 'project:write:any', 'project:admin'],
  'project.inventory.adjust': ['project:write:any', 'project:admin'],
  'project.performance.read': ['project:read:any', 'project:write:any', 'project:admin'],
  'project.document.upload': ['project:write:any', 'project:admin'],
  'project.document.download': ['project:read:any', 'project:write:any', 'project:admin'],
  'project.document.manage': ['project:write:any', 'project:admin'],
  'project.document.version': ['project:write:any', 'project:admin'],
  'project.permit.read': ['project:read:any', 'project:write:any', 'project:admin'],
  'project.permit.manage': ['project:write:any', 'project:admin'],
  'project.compliance_inspection.read': ['project:read:any', 'project:write:any', 'project:admin'],
  'project.compliance_inspection.manage': ['project:write:any', 'project:admin'],
  'project.compliance_record.read': ['project:read:any', 'project:write:any', 'project:admin'],
  'project.compliance_record.manage': ['project:write:any', 'project:admin'],
  'project.rfi.read': ['project:read:any', 'project:write:any', 'project:admin'],
  'project.rfi.create': ['project:write:any', 'project:admin'],
  'project.rfi.respond': ['project:write:any', 'project:admin'],
  'project.rfi.manage': ['project:write:any', 'project:admin'],
  'project.submittal.read': ['project:read:any', 'project:write:any', 'project:admin'],
  'project.submittal.create': ['project:write:any', 'project:admin'],
  'project.submittal.review': ['project:write:any', 'project:admin'],
  'project.submittal.manage': ['project:write:any', 'project:admin'],
  'project.quality.read': ['project:read:any', 'project:write:any', 'project:admin'],
  'project.quality.inspect': ['project:write:any', 'project:admin'],
  'project.quality.manage_deficiency': ['project:write:any', 'project:admin'],
  'project.quality.verify_corrective': ['project:write:any', 'project:admin'],
  'project.safety.read': ['project:read:any', 'project:write:any', 'project:admin'],
  'project.safety.report': ['project:write:any', 'project:admin'],
  'project.safety.investigate': ['project:write:any', 'project:admin'],
  'project.safety.manage': ['project:write:any', 'project:admin'],
};




// ── Internal helpers ──────────────────────────────────────────────────────────

function hasOrgLevelAuthority(actor: ProjectContext, action: string): boolean {
  const orgPermsRequired = ORG_LEVEL_AUTHORITY_MAP[action] ?? [];
  return orgPermsRequired.some((p) => actor.organizationMembership.permissions.includes(p));
}

function hasProjectLevelAuthority(actor: ProjectContext, action: string): boolean {
  const membership = actor.projectMembership;
  if (!membership || membership.status !== 'ACTIVE') return false;
  const caps = PROJECT_ROLE_CAPABILITIES[membership.role] ?? [];
  return caps.includes(action);
}

// ── Public policy object ──────────────────────────────────────────────────────

export const projectPolicy = {
  /**
   * Authorizes an actor for a given action using the three-case model:
   *   Case 1 — org-level authority (org admin / cross-project permissions)
   *   Case 2 — project-scoped authority (active membership + role capability)
   *   Case 3 — deny (throws ProjectForbiddenError)
   */
  authorize({ actor, action }: { actor: ProjectContext; action: string }): void {
    // Case 1: org-level authority grants cross-project access
    if (hasOrgLevelAuthority(actor, action)) return;

    // Case 2: project-scoped membership authority
    if (hasProjectLevelAuthority(actor, action)) return;

    // Case 3: deny
    throw new ProjectForbiddenError(`Missing authority for action: ${action}`);
  },

  /**
   * Returns true/false without throwing — useful for conditional logic.
   */
  can({ actor, action }: { actor: ProjectContext; action: string }): boolean {
    return hasOrgLevelAuthority(actor, action) || hasProjectLevelAuthority(actor, action);
  },
};
